### ISSUE TITLE
chromeにて印刷プレビュ画面のキャプチャが取得できない。

### ISSUE THREAD

**Issue by jjcall0904** [hifive/hifive-pitalium#112]
印刷プレビュ画面のキャプチャを取得しようとすると
裏側の画面のキャプチャが取得されます。

ScreenshotArgument arg = ScreenshotArgument.builder("印刷プレビュ画面").addNewTarget().build();
assertionView.verifyView(arg);

印刷プレビュ画面のキャプチャを取得する方法はないのでしょうか？

**Comment by tkashi** [comment]
ご質問ありがとうございます。

印刷プレビュ画面とは、各ブラウザの機能で現れる画面ということでよろしいでしょうか。
（今回だとChromeのメニューから印刷を選択して開かれる画面）

残念ながら、この画面はブラウザの機能であるため、Seleniumのサポート外となりPitaliumではスクリーンショットを撮れません。

Javaで取得したい場合、ローカル限定になりますが、java.awt.Robotを使えばスクリーンショットを撮ることもできます。
下記のようなコードでブラウザの撮影ができることを確認しています。

```
  Point pos = driver.manage().window().getPosition();
  Dimension size = driver.manage().window().getSize();
  
  // キャプチャの範囲
  Rectangle bounds = new Rectangle(pos.getX(), pos.getY(), size.getWidth(), size.getHeight());
  
  Robot robot;
  try {
	robot = new Robot();
	BufferedImage image = robot.createScreenCapture(bounds);
	// 以下、出力処理
	String dirName = "C:\\Users\\ken\\Desktop\\";
	SimpleDateFormat format = new SimpleDateFormat("yyyyMMddHHmmss");
	String fileName = "test_" + format.format(new Date()) + ".jpg";
	ImageIO.write(image, "jpg", new File(dirName, fileName));
  } catch (AWTException e1) {
	// TODO 自動生成された catch ブロック
	e1.printStackTrace();
  } catch (IOException e) {
	// TODO 自動生成された catch ブロック
	e.printStackTrace();
  }
```

ただし、これはブラウザ自体を撮影しているため、可視範囲しか撮れないことにご注意ください。
また、最初の記述の通り、RobotはJUnitを起動しているマシンでしか動作しないため、リモートのブラウザのスクリーンショットを取得することはできません。

もし印刷した結果を確認したいということであれば、上記Robotはキーボード操作をエミュレートできるので、例えば `robot .keyPress(KeyEvent.Enter);` などでEnterキーをエミュレートして、印刷プレビューの印刷ボタンを押下させてPDFなどで出力させる方法でもできると思います。

**Comment by jjcall0904** [comment]
返信が遅くなりまして大変申し訳ございません。

詳細な返信ありがとうございます。
記載していただきましたコードを実行しましたところキャプチャの取得ができました。

感謝いたします。

PS：
こうなると「pitalium-explorer」との連携をとるためには
通常の仕組みで取得する流れと分けて実装する必要があり悩みどころですね。
Seleniumが最近になってちょくちょくバージョンがあがっていることと
geckodriverのこれから・・・など目が離せません。

**Comment by tkashi** [comment]
@jjcall0904 さん

ご返信が遅くなりまして申し訳ありません。
取得ができたということでよかったです。

独自に比較した結果のPitalium Explorerでの表示については、
結果ファイルの出力が現時点のPitaliumだと少し組みづらいので、
#119 で任意の画像を指定して結果ファイルを保存する仕組みの提供を検討いたします。
