### ISSUE TITLE
Firefoxでは縦スクロール量 < マージンの場合、画面の下がスクリーンショットに含まれない

### ISSUE THREAD

**Issue by tnakatan** [hifive/hifive-pitalium#117]
Firefox（Windows、macOS共に）で以下の条件で撮影すると、画面の下がスクリーンショットに含まれない。

* BODYの大きさが画面縦方向の大きさよりも小さい。  
  （windowHeight = 100, BODY.height = 90）
* BODYにmarginTopを、スクロールが発生する様に設定する。  
  （body.marginTop = 15）

Firefox:
![Firefoxでの撮影結果](https://cloud.githubusercontent.com/assets/11323198/24534418/e458a304-1608-11e7-95cc-cba0552ef62d.png)

IE, Chrome:
![Chromeでの撮影結果](https://cloud.githubusercontent.com/assets/11323198/24534511/721d4a1e-1609-11e7-8f0f-6cf27b875b5c.png)

**Comment by tkashi** [comment]
#120 と同じ現象
