### ISSUE TITLE
macOS Safariで横スクロールがあるページのスクリーンショットが正常に撮影できない

### ISSUE THREAD

**Issue by tnakatan** [hifive/hifive-pitalium#118]
Safariで横スクロールがあるページを撮影すると、添付画像の様に、不必要に横スクロールが行われてしまう。

環境：

* macOS Sierra
* Safari 10.2

Safari:
![Safari 10.2 (Sierra)](https://cloud.githubusercontent.com/assets/11323198/24534606/0cf81a0a-160a-11e7-9554-decf428a99b0.png)

Chrome:
![Chrome (Sierra)](https://cloud.githubusercontent.com/assets/11323198/24534630/298d5284-160a-11e7-8c04-d5618d7fa0f5.png)

**Comment by ishikawa1027** [comment]
対応済み。
