### ISSUE TITLE
類似度による比較機能の実装

### ISSUE THREAD

**Issue by tkashi** [hifive/hifive-pitalium#125]
画像の類似度を計算し、閾値を超えていれば同一とみなす比較機能を実装する

hifive/hifive-pitalium-explorer#64 に伴い、Explorerにある機能を移植する
移植する機能は以下の通り
- similarityPixelByPixel （各pixelの色の差分ノルムに基づく類似度）
- similarityFeatureMatrix (画像を5*5に分割し、各セルの特徴量を計算した行列に基づく類似度）
- similarityThresDiff (画像の重ね合わせの位置をずらして、その中で各pixelで閾値以上の色の違いがある数に基づく類似度)
- similarityTotalDiff (閾値を0としたsimiralityThresDiff)

**Comment by tkashi** [comment]
今までのImageUtilsおよびComparatorのcompareメソッドの返り値のDiffPointsは、pixelごとに比較することが前提となる返り値だったため、
汎用にするために判定結果のみを返すメソッドを持つ親クラスを作り、DiffPointsはこの子クラスとする。
今後compareメソッドの返り値は、この親クラスの子クラスとなるようにする。

**Comment by tkashi** [comment]
comparisonConfig.jsonで

```
{
	"options": [
		{
			"type": "SIMILARITY",
			"parameters": {
				"pixleByPixelThreshold": 1.0,
				"featherMatrixThreshold": 1.0,
				"thresDiffThreshold": 1.0,
				"totalDiffThreshold": 1.0
			}
		}
	]
}
```
のように各類似度の閾値(0.0〜1.0)を指定することができ、計算結果が閾値以上の値の場合は、一致とみなすようにする（1.0で完全一致の場合、0.0でどの場合でも一致とみなす）。
指定されていない場合は、0.0を指定したことと同じ（その類似度の値は使用しないこと）とする。

**Comment by sakaim** [comment]
以下が未対応。
・デフォルト値のcomparisonConfig.jsonファイルの追加
・対応するテストの追加

**Comment by ishikawa1027** [comment]
テスト追加は次リリースへの残件として改めて起票し、このissueはクローズする
