### ISSUE TITLE
結果確認画面から正解データを書き換える機能を追加する

### ISSUE THREAD

**Issue by meganetaaan** [hifive/hifive-pitalium#131]
例えばアプリを改修した後に実行したテストで、
失敗したテストケースに対して「この画像の変更は意図したものである」という場合に、
結果確認画面から正解データを書き換えられると便利です。

**Comment by tkashi** [comment]
Pitalium Explorerからの変更でしょうか？
そうであれば、hifive/hifive-pitalium-explorer#61 と同じだと思います。
（各比較結果に対して、実行結果のtrue/falseを変更できるようになります）

もしくはPitalium本体から何か変更を意図しているでしょうか？

**Comment by meganetaaan** [comment]
Pitalium Explorerからの変更です。
既にあったのですね。失礼しました。

　https://github.com/hifive/hifive-pitalium-explorer/issues/61

こちらは重複のためクローズします。
