### ISSUE TITLE
pitalium-sampleでselenium3.5.3を使うとエラーが発生

### ISSUE THREAD

**Issue by tkmHashi** [hifive/hifive-pitalium#158]
以下のエラー発生
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to com.htmlhifive.pitalium.core.selenium.PtlWebElement

PtlWebDriver$JsonToPtlWebElementConverter.applyが呼び出されたときの result が
 ArrayList<RemoteWebElement> になっている
WebElementをPtlWebElementにラップできていない

**Comment by tkmHashi** [comment]
#161

**Comment by ishikawa1027** [comment]
#161 と重複。対応済み。
