### ISSUE TITLE
IEDriverServer 3.5以降で可視範囲外が撮影されない

### ISSUE THREAD

**Issue by sakaim** [hifive/hifive-pitalium#160]
これまでIEは一度でページ全体が撮影できる仕様だったが、IEDriver 3.5から可視範囲のみになった。

ChromeやFirefoxと同様に、SplitS reenshotWebDriverベースに変更する必要がある。

**Comment by ishikawa1027** [comment]
コミット bc31191b7f0d56b814a5bf3eeb7d4fc9adb4128e で対応済み。
