### ISSUE TITLE
ChromeでassertView.assertView()を実行するとjava.lang.ClassCastExceptionが発生する

### ISSUE THREAD

**Issue by tkmHashi** [hifive/hifive-pitalium#161]
java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to com.htmlhifive.pitalium.core.selenium.PtlWebElement
が発生する

#### 現象を確認した環境
- Pitalium
    - pitlium-1.2.1
- Chrome
    - 61.0.3163.100(64bit)
- Selenium Grid サーバー
    - selenium-server-standalone-3.5.3
    - chromedriver_2.32
- Javaライブラリ
    - selenium-suppoert-3.5.3
    - selenium-remote-driver-3.5.3
    - selenium-java-3.5.3
    - selenium-chrome-driver-3.5.3
    - selenium-api-3.5.3

**Comment by tkmHashi** [comment]
### 確認環境
- Chrome
    - 62.0.3202.94(64bit)
- Selenium Gridサーバー
    - chromedriver_2.33
- 上記以外は同じ環境

### エラー内容
- java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebElement cannot be cast to com.htmlhifive.pitalium.core.selenium.PtlWebElement
    - at com.htmlhifive.pitalium.core.model.ScreenAreaWrapper.createDomWrapper([ScreenAreaWrapper.java:227](https://github.com/hifive/hifive-pitalium/blob/d74942b9e5385cce854fd575056cb57372ea23e8/pitalium/src/main/java/com/htmlhifive/pitalium/core/model/ScreenAreaWrapper.java#L227)) ~[pitalium-1.2.1.jar:?]

### エラーの詳細
- Chromeの場合のみelがRemoteWebElementになってしまう。他のブラウザでは以下のようになる。
    - Chrome
        - RemoteWebElement
    - Firefox
        - PtlFirefoxWebElement
    - IE11
        - PtlInternetExplorerWebElement
- RemoteWebDriver.java l.216 で取得しているelementsがRemoteWebElementの配列になっている。selector.findElements(driver); の呼び出しをたどると
    - RemoteWebDriver.java l.438 RemoteWebDriver#findElements が呼び出される
    - RemoteWebDriver.java l.636 RemoteWebDriver#execute が呼び出される
    - HttpCommandExecutor l.124 HttpCommandExecutor#execute が呼び出されて以下のvalueを持つResponseが返される
        - Chrome
            - RemoteWebElement配列の配列
        - Firefox, IE11
            - HashMapの配列
        - Responseを作成する処理についてexecute内で呼び出されるdecodeメソッドが異なる
            - Chrome
                - AbstractHttpResponseCodec#decode
            -  Firefox, IE11
                - W3CHttpResponseCodec#decode
    - PtlWebDriver.java l.1922 JsonToPtlWebElementConverter#apply が呼びされて上記が下記に変換される
        - Chrome
            - RemoteWebElementの配列
        - Firefox
            - PtlFirefoxWebElementの配列
        - IE11
            - PtlInternetExplorerWebElementの配列

**Comment by kou2222** [comment]
同様の現象を以下の環境で確認しました。
環境
Chrome 
・64.0.3282.167(64bit)
Selenium Gridサーバー
・chromedriver_2.33
selenium-server-standalone-3.6
Javaライブラリ
・selenium-suppoert-3.9.1
・selenium-remote-driver-3.9.1
・selenium-java-3.9.1
・selenium-chrome-driver-3.9.1
・selenium-api-3.9.1
・Pitalium pitlium-1.2.1

chromeが利用できない影響でブラウザテストだけでなく、Androidのブラウザテストも実行ができませんでした。
現時点での対応方法はありますか？
それともアップデート待ちになりますか？

**Comment by sakaim** [comment]
ご報告ありがとうございます。
本障害はSeleniumのJavaライブラリ3.5以降と組み合わせると発生するため、
現時点ではJavaライブラリを3.4.0に落とすことで回避可能です。

Pitalium次回リリース（2018/3月中を予定）で修正を予定しております。

**Comment by kou2222** [comment]
selenium-java-3.4.0.jarでも同様のエラーが発生しました。
ほかのseleniumライブラリも3.4.0に落とし実験しましたが、そちらでもエラーが発生しました。

**Comment by kou2222** [comment]
pitalium-sampleのjarにすべて書き換えた場合、正常動作しました。
なぜ3.4.0でもエラーが発生したかは謎ですが、次のpitaliumリリースを待つことにします。

**Comment by ishikawa1027** [comment]
コミット 1a41eff7c9cc60dad78af46303e956002aa08ba0 で対応済み
