### ISSUE TITLE
MacのChromeでカラーページのテストに失敗する

### ISSUE THREAD

**Issue by sakaim** [hifive/hifive-pitalium#162]
MacのChromeのみ、テスト用のグラデーションページなどで他ブラウザとは表示される色が異なっているため、テストが失敗する。

Pitalium起因ではないため、色をチェックするテストをスキップして対応する。

**Comment by ishikawa1027** [comment]
コミット 1a41eff7c9cc60dad78af46303e956002aa08ba0 で対応済み
