### ISSUE TITLE
Can not see any the screenshots on macos

### ISSUE THREAD

**Issue by Haro10** [hifive/hifive-pitalium#181]
Hi guys,

I follow the guide in the link: https://www.htmlhifive.com/conts/web/view/pitalium-tutorial/test-basic-run

But I can not see any screenshots in the test result folder.
Please help me!!! Thank you so much.

<img width="1349" alt="2018-07-20 15 52 44" src="https://user-images.githubusercontent.com/13564710/42987834-804f7e4c-8c35-11e8-9a62-b6a9dfa6a6dc.png">

**Comment by Haro10** [comment]
I also can not see the currentExpectedIds.json from the hifive-pitalium folder that downloaded by git commands.

**Comment by meganetaaan** [comment]
Hi. Thank you for trying Pitalium!
Could you give me information below?

* test code (SampleTest.java)
* config files(environmentConfig.json, capabilities.json, testAppConfig.json and persisterConfig.json)
* test log (as shown in the "Console" tab on your screenshot)

Also I will confirm if the tutorial document has any flaw.
Are you reading the English version of the doc?

**Comment by Haro10** [comment]
Hi, thank you so much for your kind.

I am reading the English version. 

I got struggle to deal with MacOs due to the fact that the doc is wirte for windows. 
Do you have any doc for MacOs?

I have attached the files you asked here [Files.zip](https://github.com/hifive/hifive-pitalium/files/2213316/Files.zip). Please help me to check it.

Thank you so much!

**Comment by meganetaaan** [comment]
Sorry we don't have MacOS version. I'm glad if you tell me which part of doc was confusing.

I've checked your configuration files.
In environmenConfig.json, I saw execMode property is set to "RUN_TEST" mode. But you should set it to "SET_EXPECTED" to collect screenshots as the expected(correct answer) image of the view in your first try.
If you run test in RUN_TEST mode without expected images then all the assertView fail.

**Comment by meganetaaan** [comment]
@Haro10 Hi, Did my suggestion solve the problem?

**Comment by Haro10** [comment]
Hi!
Sorry for replying late. I have resolved it. I don't know exactly how I fixed it, but it luckily was fixed.

If I have more information, I will contact you!

Thanks for your kind!

**Comment by meganetaaan** [comment]
Got it. I'll close this issue.
If you find another problem, don't hesitate to reopen it.
Thank you!
