### ISSUE TITLE
テストメソッドごとにdriver（ウィンドウ）を閉じるのではなく、テストクラスが終了するときにdriverを閉じるようにする

### ISSUE THREAD

**Issue by tkashi** [hifive/hifive-pitalium#21]
テストメソッドごとにdriver.quit()をしているため、各テストメソッドでウィンドウを開きなおす必要がある。
そのため、オーバーヘッドが高くテストに時間がかかる。

同一capability同一テストクラス内ではdriverを使いまわして、
オーバーヘッドを減らすようにする。

**Comment by simdy** [comment]
ドライバを閉じるタイミングは、テストクラスが終了するときが常に最適とは限らないと思われます。

* FWでは何もしない
 * ウィンドウを管理するマネージャ的なものを用意しておき、それ経由で再起動を明示的に行った場合のみ再起動する
* テストクラスごとに（自動的に）再起動する
* テストメソッドごとに再起動する

を、アノテーションや設定ファイル等で選択できるようにするのが良いかと思います。
「テストメソッドやテストクラスをどういう粒度で作るのか」や、これに関連して
「ログイン・ログアウトやDBの初期化はどのタイミングで行うのか（推奨or代表的なパターン）」など
テスト設計の観点からも考慮しつつ仕様を詳細化してください。

**Comment by tkashi** [comment]
以下のコミットで対応しています
55a2f255415baa633013c35c20a5bed9543ea203
95b492603922987ba8a193d9278a2d689bf92cec
39942bd61bf60099ac677a1692088dd7b1cac8a3
df5aaee251f8930ff03cedb758dc9a8cf32c90b1
787d1f70f47fe24e54ef97ae548fc1784111d35b
89c15e2b5d17d9f13db9960d7a68b4790f6945c1
966c5e0eef35d12652a37bddc9abdd819c9db25e

**Comment by tkashi** [comment]
Wiki側に説明を追加しました
https://www.htmlhifive.com/conts/web/view/pitalium-reference/spec#HPtlWebDriverStrategy
