### ISSUE TITLE
Targetの切り出し範囲が（上に）ずれることがある

### ISSUE THREAD

**Issue by sakaim** [hifive/hifive-pitalium#44]
Targetを指定してスクリーンショットを撮ったとき、Targetの切り出し範囲がずれ、上に1px分余計に写りこむ（AND/OR）下が1px切れることがある。
IE10でisMoveをfalseにしたときのtextarea、iframeなどで発生。
サイズが小数値のときの端数の処理の仕方でずれが起きていると思われる。

## IE10 textarea
![capture_no-move__internet explorer_10_id_textarea-scroll_ 0](https://cloud.githubusercontent.com/assets/11323125/11770611/636ac222-a246-11e5-9700-d7c9b519cc14.png)

## IE10 iframe
![capture_no-move__internet explorer_10_tag_name_iframe_ 0](https://cloud.githubusercontent.com/assets/11323125/11770625/a59a2b92-a246-11e5-8090-748bba77f29b.png)

**Comment by sakaim** [comment]
PCブラウザのずれは対応完了。
モバイル端末ではまだずれる場合がある（物理ピクセル数 <=> 論理ピクセル数 の計算時に誤差が出ているものと思われる）が、同対象に対してのスクリーンショットは毎回同じずれ方をするため、画像比較には影響しない。

**Comment by tkashi** [comment]
モバイルのずれについては#68でissueを立てました
