### ISSUE TITLE
iPhoneで部分スクロール要素を撮影したとき、切り取りサイズが途中で変わる

### ISSUE THREAD

**Issue by sakaim** [hifive/hifive-pitalium#58]
部分スクロール指定して撮影する際は
部分スクロール1回毎に全体撮影→要素切抜きを繰り返すが、
初回と2回目で切り抜くサイズが変わってしまう場合がある。
scaleの計算結果が変わってしまっていることが原因だと思われる。

iPhone 6（iOS 8）でtextareaを撮影した際に発生。

**Comment by tkashi** [comment]
1.1.0で取り込み済み
