### ISSUE TITLE
実行モードにSKIPモードを追加する

### ISSUE THREAD

**Issue by sakaim** [hifive/hifive-pitalium#79]
execMode: 'IGNORE' と指定すると assertView()の実行が無視されるようにしたい。

Seleniumのテストケースはこまめに動作確認を繰り返しながら作成/修正することが多く、その都度スクリーンショット撮影が実行されると、動作に時間がかかり作業効率が落ちてしまう。
assertView()の実行を一括でON/OFFできる機能が欲しい。

**Comment by simdy** [comment]
"IGNORE"という名前だと、「アサーション（の真偽）を無視する」のか
「画像の取得自体（取得を含めたアサーション処理全て）をスキップする」のかがわかりにくいように思います。
別の名前を検討してください。（例："SKIP"とか？）
