### ISSUE TITLE
GeckoDriverでFirefoxのスクリーンショットが可視範囲しか撮影されない

### ISSUE THREAD

**Issue by sakaim** [hifive/hifive-pitalium#82]
Firefox47から、Seleniumテストの動作にGeckoDriver (Marionette Driver) が必要になった。

GeckoDriver v0.10.0 現在では、ChromeDriver等と同様に、driver.takeScreenshot() で撮影できる範囲が可視範囲のみとなっている。
Firefoxもスクロールしながら撮影するよう、PtlFirefoxDriverを修正する。

**Comment by tkashi** [comment]
画面の横スクロールの対応ができていなかったので、再オープンします

**Comment by tkashi** [comment]
Firefoxでは問題なく、Safariでのみ横スクロールがある場合に正しく撮れていないため、
このチケットはクローズし、#103 で対応することとします
