### ISSUE TITLE
Mobileでテストコードを実行すると必ず失敗するケースが存在する

### ISSUE THREAD

**Issue by tnakatan** [hifive/hifive-pitalium#91]
### 表示されていない要素を撮影しようとして失敗するケース

* com.htmlhifive.pitalium.it.assertion.partialpage
  * CompareSamePartTest#compareSamePartByName
    - `[name=text]`
* com.htmlhifive.pitalium.it.screenshot.partialapge
  * TakeMultiplePartByMultipleTargetTest#takeMultiplePartByMultipleTarget
    - `#firstNav>ul>li`
  * TakeNoScrollPageTest#takeNoScrollPage
    - `.download`
  * TakeSinglePartBySingleTargetTest#takeScreenshotByName
    - `[name=text]`

### 画面サイズが考慮されていないケース

* com.htmlhifive.pitalium.it.screenshot.fullpage
  * ScrollLessThanMarginTopTest#testScrollLessThanMarginTop
    - ページ表示後に動的に要素を追加するため、画面がズームされた状態になってしまう。  
`<meta name="viewport" content="width=device-width, initial-scale=1">` を設定し、devicePixelRatioを考慮する。

**Comment by tkashi** [comment]
テストケースの置き換えにより対応完了済み
